### ISSUE TITLE
MInor problem with overriding

### ISSUE THREAD

**Issue by qrilka** [jaddison/django-multihost#2]
In my model I've created a field:
    site = models.ForeignKey(Site, default=Site.objects.get_current)
This field is set to readonly so I want to create Model items only for the current site. It looks like models.py gets loaded before middleware gets invoked so I get incorrect field value.
Currently I've made a workaround with
    site = models.ForeignKey(Site, default=lambda:Site.objects.get_current())
Maybe there is a nicer solution for this problem?

**Comment by jaddison** [comment]
I believe this is fixed with the merge of https://github.com/jaddison/django-multihost/pull/5 by @dannyclark.
