### ISSUE TITLE
Multihost does strange things when used in combination with debug_toolbar (fixed!!!)

### ISSUE THREAD

**Issue by foxx** [jaddison/django-multihost#3]
Hey,

So, Django does strange things (like sending requests to the wrong urls handler) when it is used in conjunction with debug_toolbar.

To fix this problem, multihost must _always_ be the last entry in MIDDLEWARE_CLASSES.

Might be worth updating the documentation about this, as I was close to dumping Multihost because of this issue!

Cal

**Comment by jaddison** [comment]
Fixed - thanks for bringing this to my attention!
